version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/docker/postgres-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: redis-container
    ports:
      - "6379:6379"

  exchangerate-service:
    image: yngridyayacalero/exchange-service:1.0
    container_name: exchange-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
